name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.12"
          - "3.13"

    name: Test with Python ${{ matrix.python_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python_version }} --dev

      - name: Check formatting with ruff
        if: matrix['python_version'] == '3.11'
        run: uv run --python ${{ matrix.python_version }} ruff format --check .

      - name: Lint with ruff
        if: matrix['python_version'] == '3.11'
        run: uv run --python ${{ matrix.python_version }} ruff check .

      - name: Check types with pyright
        if: matrix['python_version'] == '3.11'
        run: uv run --python ${{ matrix.python_version }} pyright

      - name: Run examples/000.py
        run: uv run --python ${{ matrix.python_version }} examples/000.py

      - name: Run examples/001.py
        run: uv run --python ${{ matrix.python_version }} examples/001.py

      - name: Run examples/002.py
        run: uv run --python ${{ matrix.python_version }} examples/002.py

      - name: Run examples/003.py
        run: uv run --python ${{ matrix.python_version }} examples/003.py

      - name: Run examples/004.py
        run: uv run --python ${{ matrix.python_version }} examples/004.py

      - name: Run examples/005.py
        run: uv run --python ${{ matrix.python_version }} examples/005.py
